- hosts: all
  become: true
  become_user: ubuntu
  tasks:
      - name: create new Deployment
        command: kubectl apply -f /home/ubuntu/Deployment.yaml
      - name: create new service 
        command: kubectl apply -f /home/ubuntu/Service.yaml